
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_TO_MY_DREAMS_LIST = 'REMOVE_TO_MY_DREAMS_LIST';
export const REDUCE_FROM_INVENTORY='REDUCE_FROM_INVENTORY';
export const ADD_TO_INVENTORY='ADD_TO_INVENTORY';
